[all:vars]
ansible_user=johans
ansible_password=P@ssw0rd

[routers:children]
cisco

[cisco]
jmr1lab2 ansible_host=192.168.2.36 private_ip=192.168.8.1/24 private_ip_2=192.168.8.1
jmr2lab2 ansible_host=192.168.2.37 private_ip=192.168.8.2/24 private_ip_2=192.168.9.1
jmr3lab2 ansible_host=192.168.2.38 private_ip=192.168.9.2/24 private_ip_2=192.168.10.1
jmr4lab2 ansible_host=192.168.2.39 private_ip=192.168.10.2/24 private_ip_2=192.168.10.2

[cisco:vars]
ansible_user=johans
ansible_network_os=ios
ansible_connection=network_cli
ansible_become=yes
ansible_become_method=enable
ansible_sudo_password=P@ssword

[dc1]
jmr1
jmr2