---
- name:  Lab 2 playbook
  hosts: cisco
  gather_facts: no
  
  tasks:
#Set the hostname to the hostname listed in the inventory file
    - name: Set hostname
      cisco.ios.ios_config:
        lines: hostname {{ inventory_hostname }}
#Sets a multiline login banner
    - name: Set login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          This is Johans' login banner
          Welcome to {{ inventory_hostname }}
        state: present
#Configure logging on the routers
    - name: Turn on logging
      cisco.ios.ios_logging:
        dest: console
        facility: local7
        level: debugging
        state: present
#Configure the vmnet10 interfaces (g2/0) on both routers using the layer 3 ansible package using the private_ip variable contained in the host file
    - name: Configure interface IP
      cisco.ios.ios_config:
        lines: "{{ ipset }}"
#Turn on router level ospf and add the two networks (management and vmnet10) to the ospf (process 1) and make the part of area 0
    - name: Enable router-level OSPF
      cisco.ios.ios_config:
        lines: "{{ ospf_config }}"
        parents: router ospf 1
    

